

INSERT INTO country values('','United States','US');
INSERT INTO country values('','United Kingdom','GB');
INSERT INTO country values('','Canada','CA');
INSERT INTO country values('','Australia','AU');
INSERT INTO country values('','Afghanistan','AF');
INSERT INTO country values('','Albania','AL');
INSERT INTO country values('','Algeria','DZ');
INSERT INTO country values('','American Samoa','AS');
INSERT INTO country values('','Andorra','AD');
INSERT INTO country values('','Angola','AO');
INSERT INTO country values('','Anguilla','AI');
INSERT INTO country values('','Antarctica','AQ');
INSERT INTO country values('','Antigua and Barbuda	','AG');
INSERT INTO country values('','Argentina','AR');
INSERT INTO country values('','Armenia','AM');
INSERT INTO country values('','Aruba','AW');
INSERT INTO country values('','Australia','AU');
INSERT INTO country values('','Austria','AT');
INSERT INTO country values('','Azerbaijan','AZ');
INSERT INTO country values('','Bahamas','BS');
INSERT INTO country values('','Bahrain','BH');
INSERT INTO country values('','Bangladesh','BD');
INSERT INTO country values('','Barbados','BB');
INSERT INTO country values('','Belarus','BY');
INSERT INTO country values('','Belgium','BE');
INSERT INTO country values('','Belize','BZ');
INSERT INTO country values('','Benin','BJ');
INSERT INTO country values('','Bermuda','BM');
INSERT INTO country values('','Bhutan','BT');
INSERT INTO country values('','Bolivia','BO');
INSERT INTO country values('','Bosnia and Herzegovina','BA');
INSERT INTO country values('','Botswana','BW');
INSERT INTO country values('','Brazil','BR');
INSERT INTO country values('','British Indian Ocean','IO');
INSERT INTO country values('','Brunei','BN');
INSERT INTO country values('','Bulgaria','BG');
INSERT INTO country values('','Burkina Faso','BF');
INSERT INTO country values('','Burma (Myanmar)','MM');
INSERT INTO country values('','Burundi','BI');
INSERT INTO country values('','Cambodia','KH');
INSERT INTO country values('','Cameroon','CM');
INSERT INTO country values('','Canada','CA');
INSERT INTO country values('','Cape Verde','CV');
INSERT INTO country values('','Cayman Islands','KY');
INSERT INTO country values('','Central African Republic','CF');
INSERT INTO country values('','Chad','TD');
INSERT INTO country values('','Chile','CL');
INSERT INTO country values('','China','CN');
INSERT INTO country values('','Christmas Island','CX');
INSERT INTO country values('','Cocos (Keeling) Islands','CC');
INSERT INTO country values('','Colombia','CO');
INSERT INTO country values('','Comoros','KM');
INSERT INTO country values('','Congo, Democratic Republic of the','CD');
INSERT INTO country values('','Congo, Republic of the','CG');
INSERT INTO country values('','Cook Islands','CK');
INSERT INTO country values('','Costa Rica','CR');
INSERT INTO country values('','Croatia','HR');
INSERT INTO country values('','Cyprus','CY');
INSERT INTO country values('','Czech Republic','CZ');
INSERT INTO country values('','Denmark','DK');
INSERT INTO country values('','Djibouti','DJ');
INSERT INTO country values('','Dominica','DM');
INSERT INTO country values('','Dominican Republic','DO');
INSERT INTO country values('','East Timor','TL');
INSERT INTO country values('','Ecuador','EC');
INSERT INTO country values('','Egypt','EG');
INSERT INTO country values('','El Salvador','SV');
INSERT INTO country values('','Equatorial Guinea','GQ');
INSERT INTO country values('','Eritrea','ER');
INSERT INTO country values('','Estonia','EE');
INSERT INTO country values('','Ethiopia','ET');
INSERT INTO country values('','Falkland Islands (Malvinas)','FK');
INSERT INTO country values('','Faroe Islands','FO');
INSERT INTO country values('','Fiji','FJ');
INSERT INTO country values('','Finland','FI');
INSERT INTO country values('','France','FR');
INSERT INTO country values('','French Guiana','GF');
INSERT INTO country values('','French Polynesia','PF');
INSERT INTO country values('','Gabon','GA');
INSERT INTO country values('','Gambia','GM');
INSERT INTO country values('','Georgia','GE');
INSERT INTO country values('','Germany','DE');
INSERT INTO country values('','Ghana','GH');
INSERT INTO country values('','Gibraltar','GI');
INSERT INTO country values('','Greece','GR');
INSERT INTO country values('','Greenland','GL');
INSERT INTO country values('','Grenada','GD');
INSERT INTO country values('','Guadeloupe','GP');
INSERT INTO country values('','Guam','GU');
INSERT INTO country values('','Guatemala','GT');
INSERT INTO country values('','Guinea','GN');
INSERT INTO country values('','Guinea-Bissau','GW');
INSERT INTO country values('','Guyana','GY');
INSERT INTO country values('','Haiti','HT');
INSERT INTO country values('','Honduras','HN');
INSERT INTO country values('','Hong Kong','HK');
INSERT INTO country values('','Hungary','HU');
INSERT INTO country values('','Iceland','IS');
INSERT INTO country values('','India','IN');
INSERT INTO country values('','Indonesia','ID');
INSERT INTO country values('','Iraq','IQ');
INSERT INTO country values('','Ireland','IE');
INSERT INTO country values('','Israel','IL');
INSERT INTO country values('','Italy','IT');
INSERT INTO country values('','Ivory Coast','CI');
INSERT INTO country values('','Jamaica','JM');
INSERT INTO country values('','Japan','JP');
INSERT INTO country values('','Jordan','JO');
INSERT INTO country values('','Kazakhstan','KZ');
INSERT INTO country values('','Kenya','KE');
INSERT INTO country values('','Kiribati','KI');
INSERT INTO country values('','Korea, South','KR');
INSERT INTO country values('','Kuwait','KW');
INSERT INTO country values('','Kyrgyzstan','KG');
INSERT INTO country values('','Laos','LA');
INSERT INTO country values('','Latvia','LV');
INSERT INTO country values('','Lebanon','LB');
INSERT INTO country values('','Lesotho','LS');
INSERT INTO country values('','Liberia','LR');
INSERT INTO country values('','Liechtenstein','LI');
INSERT INTO country values('','Lithuania','LT');
INSERT INTO country values('','Luxembourg','LU');
INSERT INTO country values('','Macau','MO');
INSERT INTO country values('','Macedonia, Republic of','MK');
INSERT INTO country values('','Madagascar','MG');
INSERT INTO country values('','Malawi','MW');
INSERT INTO country values('','Malaysia','MY');
INSERT INTO country values('','Maldives','MV');
INSERT INTO country values('','Mali','ML');
INSERT INTO country values('','Malta','MT');
INSERT INTO country values('','Marshall Islands','MH');
INSERT INTO country values('','Martinique','MQ');
INSERT INTO country values('','Mauritania','MR');
INSERT INTO country values('','Mauritius','MU');
INSERT INTO country values('','Mayotte','YT');
INSERT INTO country values('','Mexico','MX');
INSERT INTO country values('','Micronesia','FM');
INSERT INTO country values('','Moldova','MD');
INSERT INTO country values('','Monaco','MC');
INSERT INTO country values('','Mongolia','MN');
INSERT INTO country values('','Montserrat','MS');
INSERT INTO country values('','Morocco','MA');
INSERT INTO country values('','Mozambique','MZ');
INSERT INTO country values('','Namibia','NA');
INSERT INTO country values('','Nauru','NR');
INSERT INTO country values('','Nepal','NP');
INSERT INTO country values('','Netherlands','NL');
INSERT INTO country values('','Netherlands Antilles','AN');
INSERT INTO country values('','New Caledonia','NC');
INSERT INTO country values('','New Zealand','NZ');
INSERT INTO country values('','Nicaragua','NI');
INSERT INTO country values('','Niger','NE');
INSERT INTO country values('','Nigeria','NG');
INSERT INTO country values('','Niue','NU');
INSERT INTO country values('','Norfolk Island','NF');
INSERT INTO country values('','Northern Mariana Islands','MP');
INSERT INTO country values('','Norway','NO');
INSERT INTO country values('','Oman','OM');
INSERT INTO country values('','Pakistan','PK');
INSERT INTO country values('','Palau','PW');
INSERT INTO country values('','Palestinian Territory','PS');
INSERT INTO country values('','Panama','PA');
INSERT INTO country values('','Papua New Guinea','PG');
INSERT INTO country values('','Paraguay','PY');
INSERT INTO country values('','Peru','PE');
INSERT INTO country values('','Philippines','PH');
INSERT INTO country values('','Pitcairn Island','PN');
INSERT INTO country values('','Poland','PL');
INSERT INTO country values('','Portugal','PT');
INSERT INTO country values('','Puerto Rico','PR');
INSERT INTO country values('','Qatar','QA');
INSERT INTO country values('','Réunion','RE');
INSERT INTO country values('','Romania','RO');
INSERT INTO country values('','Russia','RU');
INSERT INTO country values('','Rwanda','RW');
INSERT INTO country values('','Saint Helena','SH');
INSERT INTO country values('','Saint Kitts and Nevis','KN');
INSERT INTO country values('','Saint Lucia','LC');
INSERT INTO country values('','Saint Pierre and Miquelon','PM');
INSERT INTO country values('','Saint Vincent and the Grenadines','VC');
INSERT INTO country values('','Samoa','WS');
INSERT INTO country values('','San Marino','SM');
INSERT INTO country values('','São Tome and Principe','ST');
INSERT INTO country values('','Saudi Arabia','SA');
INSERT INTO country values('','Senegal','SN');
INSERT INTO country values('','Serbia and Montenegro','CS');
INSERT INTO country values('','Seychelles','SC');
INSERT INTO country values('','Sierra Leone','SL');
INSERT INTO country values('','Singapore','SG');
INSERT INTO country values('','Slovakia','SK');
INSERT INTO country values('','Slovenia','SI');
INSERT INTO country values('','Solomon Islands','SB');
INSERT INTO country values('','Somalia','SO');
INSERT INTO country values('','South Africa','ZA');
INSERT INTO country values('','South Georgia and the South Sandwich Islands','GS');
INSERT INTO country values('','Spain','ES');
INSERT INTO country values('','Sri Lanka','LK');
INSERT INTO country values('','Suriname','SR');
INSERT INTO country values('','Svalbard and Jan Mayen','SJ');
INSERT INTO country values('','Swaziland','SZ');
INSERT INTO country values('','Sweden','SE');
INSERT INTO country values('','Switzerland','CH');
INSERT INTO country values('','Taiwan','TW');
INSERT INTO country values('','Tajikistan','TJ');
INSERT INTO country values('','Tanzania','TZ');
INSERT INTO country values('','Thailand','TH');
INSERT INTO country values('','Togo','TG');
INSERT INTO country values('','Tokelau','TK');
INSERT INTO country values('','Tonga','TO');
INSERT INTO country values('','Trinidad and Tobago','TT');
INSERT INTO country values('','Tunisia','TN');
INSERT INTO country values('','Turkey','TR');
INSERT INTO country values('','Turkmenistan','TM');
INSERT INTO country values('','Turks and Caicos Islands','TC');
INSERT INTO country values('','Tuvalu','TV');
INSERT INTO country values('','Uganda','UG');
INSERT INTO country values('','Ukraine','UA');
INSERT INTO country values('','United Arab Emirates','AE');
INSERT INTO country values('','United Kingdom','GB');
INSERT INTO country values('','United States','US');
INSERT INTO country values('','United States Minor Outlying Islands','UM');
INSERT INTO country values('','Uruguay','UY');
INSERT INTO country values('','Uzbekistan','UZ');
INSERT INTO country values('','Vanuatu','VU');
INSERT INTO country values('','Vatican City','VA');
INSERT INTO country values('','Venezuela','VE');
INSERT INTO country values('','Vietnam','VN');
INSERT INTO country values('','Virgin Islands, British','VG');
INSERT INTO country values('','Virgin Islands, U. S.','VI');
INSERT INTO country values('','Wallis and Futuna','WF');
INSERT INTO country values('','Western Sahara','EH');
INSERT INTO country values('','Yemen','YE');
INSERT INTO country values('','Zambia','ZM');
INSERT INTO country values('','Zimbabw','ZW');
